### ISSUE TITLE
Use 0.x versions

### ISSUE THREAD

**Issue by bpolaszek** [reactphp/async#23]
Hello there,

Now that react/async is open to public, would you consider using 0.x.x versions until 1.0 is not finalized instead of relying on commit hashes?

It took me a while after realizing an important BC break introduced by https://github.com/reactphp/async/commit/4355fcf8a3bdabfdc5a39362851db6ad3f441cbf after a composer update 🤠

With a semver-like approach, BC breaks would be easier to spot. WDYT?

**Comment by WyriHaximus** [comment]
Hey @bpolaszek, do you mean this [`v1.0.0`](https://github.com/reactphp/async/releases/tag/v1.0.0) that was tagged back in 2013 😜 ? We're working on `v2`, `v3`, and `v4` simultaneously where `v4` will be PHP 8.1+ only and while the branches for `v2` and `v3` are fairly stable at this point. The main branch containing the code for `v4` is not as stable as the others and is as such not release ready. But I get where you're coming from and I would suggest subscribing to this repository so you're aware of any potential breaking changes. AFAIK we don't have any other breaks planned and upcoming changes are most likely only internal.

**Comment by bpolaszek** [comment]
Oh, sorry I didn't notice that 😅 
It's not a matter of subscribing to updates, because I have a [project](https://github.com/bpolaszek/freddie) that can be used as a lib (a Symfony bundle) - meaning composer.lock won't be read in that use case and [latest dev-main commit](https://github.com/bpolaszek/freddie/blob/main/composer.json#L23) will be fetched.
I could enforce a specific commit into composer.json to avoid this (I'll probably do that), but that's not convenient either for obvious reasons 🙂

**Comment by WyriHaximus** [comment]
> It's not a matter of subscribing to updates, because I have a [project](https://github.com/bpolaszek/freddie) that can also be used as a lib (a Symfony bundle) - meaning composer.lock won't be read in that use case and [latest dev-main commit](https://github.com/bpolaszek/freddie/blob/main/composer.json#L23) will be fetched. 

Ow that is pretty neat :+1: 

> I could enforce a specific commit into composer.json to avoid this (I'll probably do that), but that's not convenient either for obvious reasons slightly_smiling_face

For now, that is your safest bet. Using a `dev-BRANCH` is never convenient :zipper_mouth_face: . But we're planning to speed up development of this package very soon :slightly_smiling_face:

**Comment by clue** [comment]
What @WyriHaximus said! ☝️

I think we all agree that we want to get a stable version out as soon as possible and that using a development version is not exactly ideal. Unfortunately, this project always has a (somewhat outdated) v1 release, so there's no reasonable way for us to ship a v0.x at this point. We could release a number of alpha/beta candidates, but at this point I would rather focus on getting the stable release out rather than working on a new release process for temporary development versions.

Rest assured we'll ship this as soon as possible and I don't think there are any major blockers at the moment or any other planned BC breaks. I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can always reopen this :+1:

**Comment by bpolaszek** [comment]
No worries - [action taken](https://github.com/bpolaszek/freddie/blob/main/composer.json#L23)! 👍
